# Generated by Django 5.1.3 on 2024-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='talla',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
